### ISSUE TITLE
Your RSS feed is slightly broken

### ISSUE THREAD

**Issue by mthurman** [markcerqueira/markcerqueira.github.com#1]
![Image of your feed](http://i.imgur.com/fS9Mz7a.png?1)
- No title on your feed
- Images seem to be broken. I know feedbin proxies through https://github.com/atmos/camo so not 100% sure what the issue would be.

**Comment by mthurman** [comment]
And your item links (not sure what it's called) aren't working. It tried to open `http://mark.gg/mark.gg/2016/03/06/evernote-academy-perspective` for me

**Comment by markcerqueira** [comment]
I think when I upgraded to Jekyll 3, this issue was fixed. Things look good to me in the Vienna RSS reader. 

![screen shot 2017-01-09 at 3 16 31 pm](https://cloud.githubusercontent.com/assets/385415/21787600/ed73854a-d67e-11e6-8553-4733385d723c.png)

Thanks @mthurman! Hope you're doing well!
